version: '3'

services:
  # for demo purposes
  #demo:
  #image: demo-app-image
  #container_name: demo-app
  #ports:
  #- 8080:8080

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"


  grafana:
    build: ./grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PLUGINS: /app/grafana/plugins
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      # dashboards are intentionally empty
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  prometheus-data:
