global:
  scrape_interval:     15s 

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # for demo purposes
  #- job_name: 'spring-actuator'
  #metrics_path: '/actuator/prometheus' 
  #scrape_interval: 5s
  #static_configs:
  #- targets: ['demo-app:8080']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

