global:
  scrape_interval:     10s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
#  - job_name: 'pushgateway'
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']
  - job_name: node
    static_configs:
      - targets:
        - javacream.eu:9100
  - job_name: simple_java
    static_configs:
      - targets: ['javacream.eu:12345']
  - job_name: springboot
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - javacream.eu:8080
#  - job_name: 'grafana-web'
#    static_configs:
#      - targets:
#        - javacream.eu:3000
#  - job_name: 'promlens'
#    static_configs:
#      - targets:
#        - javacream.eu:8090

